### ISSUE TITLE
Can't place wisps

### ISSUE THREAD

**Issue by Zanforian** [itzTerra/GhostZ#7]
I can right click with the lantern and the wisp appears momentarily but it doesn't stay there. [Log](https://mclo.gs/BNVN4XI) Modlist is [here](https://pastebin.com/ACYaLxRd) and unchanged from last issue.

**Comment by itzTerra** [comment]
This could be a part of indented functionality to make the wisps temporary - when the lantern leaves inventory, player changes worlds, quits etc. the wisps disappear.

**Comment by Zanforian** [comment]
No, it's not that. I click to place a wisp, for a fraction of a second I can see the wisp before it nearly instantly disappears again.

**Comment by itzTerra** [comment]
I downloaded a bunch of the optimization mods and it still works for me.

Does the lantern lose durability or it resets after the wisp disappears?

**Comment by Zanforian** [comment]
It didn't lose durability and the oracle text always said 0/5 wisps.

**Comment by itzTerra** [comment]
Update: after considerable effort I found out that my wisps don't like the Origins++ mod, gonna have to look at its source, as there is nothing in the log.

**Comment by Zanforian** [comment]
Weird, but if you can't fix it I'll just get rid of that mod, I ended up not using it.

**Comment by itzTerra** [comment]
**Fixed** d8359d6c1f98ea34d78cc77f30cdd4c8d8c2ed8b

Origins++ weirdly run clear command (selecting only a specific item) every tick on every player even if the problematic origin (Deathsworn) isn't played or even enabled in the config.

I opened an issue on their repo to see if it's intended or not, anyways I fixed it on my end by checking if /clear wants to delete a Ghost Lantern specifically.

**Comment by Zanforian** [comment]
Weird, I won't say I've never written fixes like that but it just seems wildly irresponsible. The fix on your end works though so I suppose it's resolved. I also wanted to say I really like this mod, thanks for the support.
