### ISSUE TITLE
Cannot convert placeable lantern

### ISSUE THREAD

**Issue by Zanforian** [itzTerra/GhostZ#8]
REI tells me the recipe is valid but when I put the placeable version in a crafting table there's no output. [Modlist](https://pastebin.com/ACYaLxRd) still unchanged. [Log](https://mclo.gs/BNVN4XI) is also the same.

**Comment by itzTerra** [comment]
Fixed 121722a49466b87188c643ced103a0eac62b584c, will publish with #7.

**Comment by Zanforian** [comment]
Fix works, thank you.
